word_list = [
    "apple", "banana", "carrot", "dog", "elephant",
    "fence", "guitar", "hat", "island", "jacket",
    "kangaroo", "lemon", "mirror", "notebook", "orange",
    "pencil", "queen", "rabbit", "snake", "tree",
    "umbrella", "violin", "watermelon", "xylophone", "yellow",
    "zebra", "airplane", "beach", "camera", "diamond",
    "electricity", "fireworks", "garden", "hamburger", "ice cream",
    "jungle", "kitchen", "lighthouse", "mountain", "note",
    "ocean", "piano", "quilt", "rocket", "sun",
    "telephone", "universe", "vegetable", "whistle", "xylophone",
    "yacht", "zipper", "basketball", "computer", "donut",
    "elephant", "football", "giraffe", "helicopter", "internet",
    "jellyfish", "koala", "laptop", "microphone", "night",
    "octopus", "pizza", "quicksand", "rainbow", "shark",
    "television", "umbrella", "vampire", "waterfall", "xylophone",
    "yoga", "zeppelin", "astronaut", "balloon", "cactus",
    "dolphin", "eclipse", "fireplace", "garden", "hedgehog",
    "iguana", "jacket", "kettle", "lightning", "mosquito",
    "nurse", "ostrich", "penguin", "quail", "rhinoceros",
    "snowflake", "telephone", "umbrella", "volcano", "water",
    "xylophone", "yarn", "zebra", "architect", "backpack",
]